/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.0.6.0 (NJsonSchema v9.13.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface SeedListFilter {
    rowsPerPage: number;
    page: number;
    seed?: number | undefined;
    gameUpgrades?: string[] | undefined;
    earliestVersionNumber?: number | undefined;
    latestVersionNumber?: number | undefined;
    geysers?: MinGeyser[] | undefined;
}

export interface MinGeyser {
    type?: string | undefined;
    min?: number | undefined;
}

export interface SeedList {
    totalEntries?: number | undefined;
    seeds?: Seed[] | undefined;
}

export interface Seed {
    id?: string | undefined;
    creationDate: Date;
    seed?: number | undefined;
    gameUpgrade?: string | undefined;
    versionNumber?: number | undefined;
    geysers?: Geyser[] | undefined;
    spaceDestinations?: SpaceDestination[] | undefined;
    modVersion?: number | undefined;
}

export interface Geyser {
    geyserType?: string | undefined;
    eruptionRate?: number | undefined;
    activeDormancyPeriod?: number | undefined;
    dormancyPeriod?: number | undefined;
    eruptionPeriod?: number | undefined;
    activeEruptionPeriod?: number | undefined;
    posX?: number | undefined;
    posY?: number | undefined;
    calculatedOutput?: number | undefined;
}

export interface SpaceDestination {
    destinationType?: string | undefined;
    distance?: number | undefined;
}

export interface SeedBrowserFilter {
    seedNumber?: number | undefined;
    includeArchived?: boolean | undefined;
    conditions?: SeedBrowserFilterCondition[] | undefined;
    page: number;
    pageSize: number;
}

export interface SeedBrowserFilterCondition {
    type?: SeedBrowserFilterConditionType | undefined;
    objectKey?: string | undefined;
    comparator?: SeedBrowserFilterConditionComparator | undefined;
    value?: number | undefined;
}

export enum SeedBrowserFilterConditionType {
    Total_Output = "Total Output", 
    Geyser = "Geyser", 
    Planet = "Planet", 
}

export enum SeedBrowserFilterConditionComparator {
    At_least = "at least", 
    At_most = "at most", 
}