export enum GameUpgrade {
    SPACE_INDUSTRY_UPGRADE = "SPACE_INDUSTRY_UPGRADE",
    COSMIC_UPGRADE = "COSMIC_UPGRADE",
    EXPRESSIVE_UPGRADE = "EXPRESSIVE_UPGRADE",
    ROCKETRY_UPGRADE = "ROCKETRY_UPGRADE",
}
