export enum GameUpgrade {
    SPACE_INDUSTRY = "SPACE_INDUSTRY",
    COSMIC_UPGRADE = "COSMIC_UPGRADE",
    EXPRESSIVE_UPGRADE = "EXPRESSIVE_UPGRADE",
    ROCKETRY_UPGRADE = "ROCKETRY_UPGRADE",
}
