export enum GeyserType {
    GEYSER_CO2 = "GEYSER_CO2",
    GEYSER_OIL = "GEYSER_OIL",
    GEYSER_COOL_SLUSH = "GEYSER_COOL_SLUSH",
    GEYSER_WATER = "GEYSER_WATER",
    GEYSER_NATGAS = "GEYSER_NATGAS",

    VENT_CO2 = "VENT_CO2",
    VENT_CHLORINE = "VENT_CHLORINE",
    VENT_COOL_STEAM = "VENT_COOL_STEAM",
    VENT_POLLUTED_PO2 = "VENT_POLLUTED_PO2",
    VENT_HYDROGEN = "VENT_HYDROGEN",
    VENT_GERMY_PO2 = "VENT_GERMY_PO2",
    VENT_POLLUTED_H2O = "VENT_POLLUTED_H2O",
    VENT_HOT_STEAM = "VENT_HOT_STEAM",

    VOLCANO_COPPER = "VOLCANO_COPPER",
    VOLCANO_GOLD = "VOLCANO_GOLD",
    VOLCANO_IRON = "VOLCANO_IRON",
    VOLCANO_MINOR = "VOLCANO_MINOR",
    VOLCANO = "VOLCANO",

    OIL_RESERVOIR = "OIL_RESERVOIR"
}

